[package]
name = "timer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
glib = "0.17.9"
gtk = "0.17.1"
macroquad = "0.3.25"
tokio = "1.27.0"
